
---

### 📄 `.github/workflows/build-and-export.yml`

```yaml
name: Build & Export Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker build -t roon-discovery-proxy:ci .

      - name: Save image as tar
        run: docker save roon-discovery-proxy:ci -o roon-discovery-proxy.tar

      - name: Upload image tar
        uses: actions/upload-artifact@v4
        with:
          name: roon-discovery-proxy
          path: roon-discovery-proxy.tar
